spring:
  profiles: prod
  main:
    banner-mode: "off"
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    platform: postgresql
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect:  org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
cinemix:
  app:
    jwtSecret: "secretKey"
    jwtExpirationMs: 86400000


server:
  port: ${PORT:8080}
